/**
 * A simple class modeling a book with only one attribute: the number of pages.
 * In this version the number of pages is supplied by the user at time of construction.
 * Note that this class DOES define a constructor, so NO default-do-nothing
 * constructor is generated by the compiler.
 * 
 * @author cstuser
 */
public class Book2 {
        private int pages ;

    public Book2(int pages){ this.pages = pages; }
    public int getPages() {        return pages;    }
    public void setPages(int pages) {        this.pages = pages;    }
    public String toString(){ return "I'm book of " + this.pages + " pages";}
}
